suppressWarnings(library(aricode))
suppressWarnings(library(car))
suppressWarnings(library(cluster))
suppressWarnings(library(crew))
suppressWarnings(library(datacleanr))
suppressWarnings(library(data.table))
suppressWarnings(library(dendextend))
suppressWarnings(library(EflowStats)) #devtools::install_github("doi-usgs/EflowStats@v5.2.0")
suppressWarnings(library(emmeans))
suppressWarnings(library(fable))
suppressWarnings(library(feasts))
suppressWarnings(library(factoextra))
suppressWarnings(library(fastcluster))
suppressWarnings(library(forecast))
suppressWarnings(library(fpc))
suppressWarnings(library(future.apply))
suppressWarnings(library(fuzzyjoin))
suppressWarnings(library(gridExtra))
suppressWarnings(library(GGally))
suppressWarnings(library(ggcorrplot))
suppressWarnings(library(ggdendro))
suppressWarnings(library(ggforce))
suppressWarnings(library(ggnewscale))
suppressWarnings(library(ggplot2))
suppressWarnings(library(ggrepel))
suppressWarnings(library(ggridges))
suppressWarnings(library(ggtext))
suppressWarnings(library(hrbrthemes))
suppressWarnings(library(MASS))
suppressWarnings(library(Metrics))
suppressWarnings(library(multcomp))
suppressWarnings(library(multcompView))
suppressWarnings(library(mvnormtest))
suppressWarnings(library(NbClust))
suppressWarnings(library(patchwork))
suppressWarnings(library(plotly))
suppressWarnings(library(pvclust))
suppressWarnings(library(qs))
suppressWarnings(library(raster))
suppressWarnings(library(readxl))
suppressWarnings(library(Rfast))
suppressWarnings(library(rgdal))
suppressWarnings(library(rprojroot))
suppressWarnings(library(sf))
suppressWarnings(library(spatialreg))
suppressWarnings(library(spdep))
suppressWarnings(library(stringdist))
suppressWarnings(library(stringr))
suppressWarnings(library(targets))
suppressWarnings(library(terra))
suppressWarnings(library(tidyterra))
suppressWarnings(library(tsibble))
suppressWarnings(library(urca))
suppressWarnings(library(vegan))
suppressWarnings(library(viridis))
suppressWarnings(library(waddR)) #devtools::install_github("goncalves-lab/waddR")

# if (!requireNamespace("BiocManager", quietly = TRUE))
#   install.packages("BiocManager")
# BiocManager::install(c("RBGL"))
# renv::install('rags2ridges')



